### ISSUE TITLE
Komponenter kan ej tas bort från aktiva sökningar

### ISSUE THREAD

**Issue by 031simon** [Drufsen/GICU-3#3]
När en komponent lagts till till aktiva sökningar -> något är skrivs i sökfältet -> komponenen i aktiva sökningar tas bort -> komponenter från den nuarande sökningen läggs till till aktiva sökningar -> BUG: dessa kan ej tas bort från 'aktiva sökningar'

**Comment by Drufsen** [comment]
Löst av plamen
